### PR TITLE
defer db rollbacks upon transaction acquisition

### LINKED ISSUE #7: *pq.Error: pq: remaining connection slots are reserved for non-replication superuser connections
Sentry Issue: [POMU-SF-K](https://sentry.io/organizations/steiner/issues/3781783605/?referrer=github_integration)

```
*pq.Error: pq: remaining connection slots are reserved for non-replication superuser connections
  File "/opt/pomu/holodex.go", line 45, in QueueUpcomingStreams
    sentry.CaptureException(err)
  File "/tmp/pomu-go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/gocron.go", line 106, in callJobFuncWithParams
    f.Call(in)
  File "/tmp/pomu-go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/executor.go", line 92, in (*executor).start.func1.2
    callJobFuncWithParams(f.function, f.parameters)
  File "/tmp/pomu-go/pkg/mod/github.com/go-co-op/gocron@v1.15.0/executor.go", line 109, in (*executor).start.func1.3
    runJob()
  File "/tmp/pomu-go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go", line 193, in (*Group).doCall.func2
    c.val, c.err = fn()
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mellowagain**
fixes #7
ref: https://go.dev/doc/database/execute-transactions#example

### CODE REVIEW

File: holodex.go [hunk 1]
```diff
@@ -62,12 +62,14 @@ func QueueUpcomingStreams(app *Application) {
 
 			// Video already exists in db, skip it
 			if err == nil {
+				tx.Rollback()
```
Comment (mellowagain) [inline holodex.go:65]: within `holodex.go` we do not use `defer tx.Rollback()` but instead call rollbacks manually before `continue`ing as `defer`ing within a `for` loop would leak resources.

we just need to take extra care when modifying this file in the future to also call `tx.Rollback()` when continuing the loop early (before `tx.Commit`)

**Review by emily33901 — APPROVED** [review]
